# Port du microservice
server.port=8083

# Configuration Bdd
db.uri=jdbc:mysql://srv-bdens.insa-toulouse.fr:3306/projet_gei_012
db.login=projet_gei_012
db.pwd=Ohwoh2uo

# Paramètres DataSource
spring.datasource.url=${db.uri}
spring.datasource.username=${db.login}
spring.datasource.password=${db.pwd}

# Configuration JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect